name: DevSecOps-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  security_scans:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'

  image_security:
    runs-on: ubuntu-latest
    needs: security_scans
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. BUILD THE IMAGES
      - name: Build Product API Image
        run: docker build -t product-api:test ./product-api

      - name: Build Order API Image
        run: docker build -t order-api:test ./order-api

      # 2. SCAN THE IMAGES (This finds OS-level vulnerabilities)
      - name: Trivy Image Scan (Product API)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'product-api:test'
          format: 'table'
          exit-code: '0' # Don't fail yet, just show results
          severity: 'CRITICAL,HIGH'

      - name: Trivy Image Scan (Order API)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'order-api:test'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
